### ISSUE TITLE
something went wrong, no devices found

### ISSUE THREAD

**Issue by andremain** [Arbuzov/hass-broadlink-ac-mqtt#1]
Does not work.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun broadlink-ac-mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
Starting Monitor…
Stopping
something went wrong, no devices found
Starting Monitor…
Stopping
something went wrong, no devices found
Starting Monitor…
Stopping

**Here is my addon configuration file:**

service:
daemon_mode: true
update_interval: 10
self_discovery: true
bind_to_ip: false
mqtt:
host: addon_core_mosquitto
port: 1883
client_id: ac_to_mqtt
user: mqtt-user
passwd: “mypassword”
topic_prefix: /aircon
auto_discovery_topic: homeassistant
auto_discovery_topic_retain: false
discovery: false
devices:

ip: 10.10.10.139
mac: c8f742348bec
name: Living Room AC
port: 80
ip: 10.10.10.80
mac: a043b008e504
name: Office AC
port: 80
ip: 10.10.10.79
mac: a043b0088f14
name: Home Cinema AC
port: 80

**Comment by Arbuzov** [comment]
self_discovery: false at the service section should fix that problem
