### ISSUE TITLE
Issue with CPU consumption

### ISSUE THREAD

**Issue by balkonrad** [Arbuzov/hass-broadlink-ac-mqtt#8]
Hi, thanks for you hard work. Plugin work like a charm but I have noticed big CPU consumption. Take a look:

![image](https://user-images.githubusercontent.com/6885412/189647189-e3d2cff6-38f2-48d9-9d4e-e1ef214caa2e.png)

Can you check what the problem is?

**Comment by oopiicaa** [comment]
Anything special in the Log tab of the add-on?

**Comment by balkonrad** [comment]
Only that kind of messages
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun broadlink-ac-mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...
(200, ('192.168.1.103', 80))
Stopping
Starting Monitor...`

**Comment by balkonrad** [comment]
and.... almost in the same time:

![image](https://user-images.githubusercontent.com/6885412/191585531-9099dcb9-f828-4682-83df-a9a7cc377660.png)

This is constant - I'm not observing any changes when it comes to this consumption %.

**Comment by oopiicaa** [comment]
Sorry, I don't understand - is high CPU usage constant or not? Or does it spike at one point and stays high?

**Comment by balkonrad** [comment]
High CPU usage is constant from my observations. It jumps up to 45% immediately after starting and doesn't drop even after 5 minutes.

**Comment by balkonrad** [comment]
Closed - new version of HA Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.3

seems to fix this problem.

**Comment by balkonrad** [comment]
Close
